{{- if .Values.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "prometheus-process-exporter.fullname" . }}
  namespace: monitoring
  labels:
{{ include "prometheus-process-exporter.labels" . | indent 4 }}
subsets:
  - addresses:
      {{- range .Values.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
{{- end }}
